### ISSUE TITLE
CJ4-  Charts not working properly

### ISSUE THREAD

**Issue by KevyKevTPA** [Working-Title-MSFS-Mods/fspackages#1001]
So, I had my charts working, but something happened and now they're not.

I'm on the latest and greatest CJ4 version, I have synced and logged in with both Simbrief and Navigraph, confirmed by their webpage.  Even after getting a clearance, and entering my SID into the route provided by Simbrief, when I hit "Lower Menu" in an effort to get my charts working, there is nothing there related to charts, just the same old lower menu.  This has survived several reboots and restarts of the sim, including a from the top import of the flight plan, etc..

I have no idea what's gone wrong, but I could use some help.

Thanks and regards,
KM

**Comment by dga711** [comment]
Just try to relink your navigraph account from MOD SET and force a flightplan change

**Comment by kmoze2001** [comment]
I'll try that as soon as possible and advise.  Thanks.

**Comment by kmoze2001** [comment]
I've tried so many troubleshooting steps that I lost myself.  And one minute it works and the next it doesn't.  For a minute, I thought it was something in my Community folder, but turns out it wasn't that.  Then I thought it was starting on the runway vs. in parking, but it's not that.  I've uninstalled and reinstalled the mod half a dozen times, reconnected to Navigraph at least as many, changed flightplans, locations, reset the sim, rebooted, you name it, and no matter what I've done, I can't find a commonality to help me narrow this down.  It feels like it's messing with me for giggles, and I'm just mentally done for the moment.

I'm not sure why you closed this, I can't see it even being possible that I'm the only person struggling with this, but I'm stumped.  If you have suggestions, please throw them at me, otherwise I'll try to revisit this when I'm not so drained and see if I can figure out wtf is happening.

If you have any suggestions, by all means throw them at me!

**Comment by mattnischan** [comment]
Did you hit the CHARTS button before hitting LWR MENU, and are you sure you have the right version installed?
