### ISSUE TITLE
[CJ4] Possible to seperate left/right fms

### ISSUE THREAD

**Issue by Gazzareth** [Working-Title-MSFS-Mods/fspackages#1076]
Not sure if it's a limitation of the Sim, but is it possible to separate the left & right fms screens to allow different screens up at the same time?

Cheers,

G

**Comment by mattnischan** [comment]
@Gazzareth It isn't a limitation of the sim, but it isn't on our immediate roadmap due to the way the stock FMSs were originally designed code-wise, which doesn't lend to separating them terribly easily. Additionally, there would be some performance hit from the rendering of the second FMS, and we would like to tackle optimizing the instruments before starting to separate them.

Nonetheless, it is on the list still to do at some point in the future.

**Comment by Gazzareth** [comment]
Thanks for the info, just used to watching P1D using "Tune" on his second FMS !!

Regards,

G
