### ISSUE TITLE
CJ4 - 0.12 - Incorrect altitude display on Logitech multi-panel

### ISSUE THREAD

**Issue by mikebakke** [Working-Title-MSFS-Mods/fspackages#1099]
This issue only manifests in 0.12 - 11.3 works as it always did.

When spinning the hardware dial to select target ALT the sim updates correctly on the FMA but the hardware display shows either 5000 or 50000 ft. 

V/S and IAS update both sim and h/w displays correctly, it is only ALT and in other a/c, all functions work as expected.

I mentioned in the Discord and got the (kinda expected) response that I should be using SPAD or AOS and this is due to a change in internal vars as part of the ongoing a/p refinement.

Could I please just get a definitive statement that this is the way I need to go before I consider whether to or not? It's not really the money, it's just adding another layer of s/w complexity to my already messy eco-system and then having to struggle to code a working template for various planes.

It's not a P1 issue and if it could be resolved in the next or later releases I can live with that and just not look at the nice legible display instead of the FMA :-)

Many thanks for the answer AND the incredible work on this plane!

**Comment by cwburnett** [comment]
This issue is that there are multiple altitude slots in the sim to accommodate functions like vnav, altitude lock, etc. 

("AUTOPILOT ALTITUDE LOCK VAR", "feet")
("AUTOPILOT ALTITUDE LOCK VAR:1", "feet")
("AUTOPILOT ALTITUDE LOCK VAR:2", "feet")
("AUTOPILOT ALTITUDE LOCK VAR:3", "feet")

By default, your hardware is probably looking at ("AUTOPILOT ALTITUDE LOCK VAR", "feet") when it should actually look at ("AUTOPILOT ALTITUDE LOCK VAR:1", "feet") for the selected altitude. So, when you turn the altitude knob with a mouse it only changes ("AUTOPILOT ALTITUDE LOCK VAR:1", "feet") and that's what your hardware should display. If your hardware can't, by default, display the indexed var ("AUTOPILOT ALTITUDE LOCK VAR:1", "feet"), then you would need to use another third party app to read and display that data.

Unfortunately, none of us use your particular hardware, so we can't give you a definitive answer on what solution would be best for your setup.

There is a free demo of Axis and Ohs that I believe supports this capability from some other discussions I've seen in the #hardware channel in Discord, but I'm not sure.

I do use Axis and Ohs for my Honeycomb Bravo, though, for controlling the AP modes, etc. and it works well for that purpose.

**Comment by mikebakke** [comment]
Thanks for the clear explanation - as I said I'll wait till I see a sample profile that's known to be working with CJ4 before trying to figure it out. 

Cheers

**Comment by juyttewaal** [comment]
Do any of the WT developers use the Stream Deck? Because it's the same issue there with Stream Deck plugin. The ALT button value returns automatically to -5000 feet, whereas the altitude displays correctly on the PFD.
Hope a solution can be found, I am staying with version 11.3 for the moment. Great work overall though, really appreciate all that WT has implemented for the CJ4.

**Comment by mattnischan** [comment]
@juyttewaal One of the WT devs does, but it isn't a bug that this is happening. The plane is no longer using the default altitude capture system from the sim, and at this time the sim SDK doesn't allow us to write to the default autopilot vars with our own information.

The solution in this case is to configure your software for the desired hardware you use. There's so much hardware and each software solution is totally different, so we can't support it directly. We can only tell you what alternative vars and events to read. The configuration has to be up to the user.

**Comment by juyttewaal** [comment]
Thank you, I appreciate your quick response, which I totally understand.


-----Original Message-----

**Comment by mikebakke** [comment]
Closing as there seems to be no issue which can be resolved in the current eco-system. If the sim APIs allow writing the custom vars in future, it'd be great if that was done and enable out of the box hardware to work.

Cheers
