### ISSUE TITLE
CJ4 - Incorrect TAS while on the ground

### ISSUE THREAD

**Issue by becas22** [Working-Title-MSFS-Mods/fspackages#1117]
![image](https://user-images.githubusercontent.com/11005754/115074783-136b3780-9ef2-11eb-9f60-8826145cfadf.png)

While on the ground, with GS zero, TAS should be zero and shouldn't be influenced by the wind.
As you can see from the image, TAS more or less corresponds to the IAS, which is incorrect.

This is not the first time I see this behaviour.

**Comment by K20017** [comment]
TAS is based on IAS and is showing you the speed of the aircraft moving through the airmass.  So it would show a value on the ground if you have a big enough headwind.

**Comment by mattnischan** [comment]
@becas22 As K2 explains, this behavior is correct. There is a 15 knot headwind, thus the true airspeed of the plane through the air is 15kts. IAS measures dynamic pressure, which on the ground is equal to the true airspeed. However, as the aircraft rises, the dynamic pressure will lessen due to ambient density. This will show as a decrease in IAS for the same TAS.

Again, on the ground, they will be effectively equal, therefore any wind will change both IAS and TAS. Perhaps you were thinking of groundspeed, which is indeed not affected in this scenario.

Hopefully that's helpful and clears up any misunderstanding!

**Comment by becas22** [comment]
You are correct. Now I feel bad for mixing these things up. Thanks!
Need to review my ATP knowledge :D

**Comment by mattnischan** [comment]
No worries at all, always happy to answer!
