### ISSUE TITLE
G3000 Abandoned current "Direct-TO" leg and intercepted original flight plan leg

### ISSUE THREAD

**Issue by N754DW** [Working-Title-MSFS-Mods/fspackages#1150]
Version 0.6.1

Departed KPWT to the south. A few miles south of the airport, turned towards SEA VOR, selected SEA in the flight plan, and activated "Direct-To". GPS correctly redrew magenta line from my position at that point to the VOR, and I activated NAV mode to follow it.

While I was selecting approach at my destination in the FMS, I looked up and the aircraft was flying a heading to intercept the original KPWT-SEA leg; it intercepted the leg and followed it to SEA VOR.

![Qxs3E6FtJQ](https://user-images.githubusercontent.com/72550869/116474595-53111800-a83e-11eb-9f62-d2703b905477.png)

**Comment by cywang90** [comment]
It's a bug in the default flight plan manager (which the g3000 still uses) that if you change any part of your flight plan while a direct to is active, the autopilot will revert to flying the flight plan instead of the direct to. A workaround is to reactivate the direct to after changing the flight plan.

**Comment by N754DW** [comment]
Thanks for the info!

**Comment by cywang90** [comment]
No problem. Closing this since it is a base sim issue and not a mod issue.
