### ISSUE TITLE
[CJ4] MCDU Black screen bug

### ISSUE THREAD

**Issue by Wardup** [Working-Title-MSFS-Mods/fspackages#1162]
Hi, I'm often facing a black screen on the MCDU while entering some approaches. Usually it starts when the approach needs to be selected twice but even after that impossible to confirm the approach. Then if i switch to other pages the MCDU doesn't display anything.
I noticed it also happens often after a missed approach procedure when I enter a new procedure.

https://streamable.com/c2a4j8

In the video the flight was LFBZ-EDLP
Route : VAVIX UN857 BEBIX UM129 EPL UM624 ROUSY M624 DIK N853 ARCKY T853 NVO M170 PADBA

**Comment by dga711** [comment]
So. While in your video it takes unusually long for the approach to load, you have to wait until its fully loaded.
So the "Working..." should be gone and the approach is selected green.

Since you are pressing again in between you are destroying the flight plan which in some cases the FMS can't handle.
