### ISSUE TITLE
G300/Longitude Issues when entering some ILS procedures from STAR also not capturing LOG/GS after HDG mode

### ISSUE THREAD

**Issue by daveblackuk** [Working-Title-MSFS-Mods/fspackages#1183]
Hi

I am flying the Longitude with latest release of the excellent G3000 mod and Longitude Performance and Flight Dynamics Modifications Project Version 1.83. Been noticing two issues:

Loading certain ILS procedures creates an overlap between the end of the STAR and start of the ILS procedure - when this occurs the aircraft starts to turn back to  re fly the last leg in the STAR - if you fly the following 

SAM N63 LELNA JSY1W EGJJ-RW26

The aircraft will fly JSY1W STAR but turn back north clockwise to ANGLA when reaching JSY as opposed to flying on to the D8.5 fix on the ILS procedure , I have flow this twice and noted the same problems. I am not sure if the data is wrong in the STAR/Approach or is an issue with the G3000.

Another issue noted was that after ATC vectors on heading mode the ILS failed to capture either LOC or GS when going back to NAV1/APPR mode. I have seen this issue with earlier versions of the Mod in the TBM but not in the Longitude.

![image](https://user-images.githubusercontent.com/4178804/118819950-b9bdaa80-b8ad-11eb-8016-a3f1aca17b93.png)
![image](https://user-images.githubusercontent.com/4178804/118820018-c80bc680-b8ad-11eb-9a30-916b103052e2.png)

ATC then gave me vectors to ILS 26 - but could not capture GS/LOC on APPR mode

![image](https://user-images.githubusercontent.com/4178804/118820594-52542a80-b8ae-11eb-80cc-7fd0c2a1a3f8.png)

**Comment by cywang90** [comment]
The approach "fly back" bug is an issue with the sim's built-in flight plan management/autopilot systems. The mod has no control over that, and the only way to fix it would be to use a completely custom FMS/AP like the CJ4 does. This is not planned in the near future, but one of the goals of WT's collaboration with Asobo/MS is to overhaul the base AP to fix these kinds of bugs.

The AP not capturing the GS from HDG mode is also a base sim issue. Essentially, you need to arm APR mode from NAV mode (make sure APR mode is not active or armed, then activate NAV mode, then arm APR mode) to get the system to reliably capture the GS.

Since these are bugs with the base sim, I will close this issue for now.

**Comment by daveblackuk** [comment]
> The approach "fly back" bug is an issue with the sim's built-in flight plan management/autopilot systems. The mod has no control over that, and the only way to fix it would be to use a completely custom FMS/AP like the CJ4 does. This is not planned in the near future, but one of the goals of WT's collaboration with Asobo/MS is to overhaul the base AP to fix these kinds of bugs.
> 
> The AP not capturing the GS from HDG mode is also a base sim issue. Essentially, you need to arm APR mode from NAV mode (make sure APR mode is not active or armed, then activate NAV mode, then arm APR mode) to get the system to reliably capture the GS.
> 
> Since these are bugs with the base sim, I will close this issue for now.

Charles

thanks, I'll stick with heading mode for now when in doubt. Great work and thanks
