### ISSUE TITLE
[G3000]'Load Airway' button greyed out on last point of SID

### ISSUE THREAD

**Issue by RomeoMikeFox** [Working-Title-MSFS-Mods/fspackages#1186]
Using the dev version of the G3000 v0.7, the Load Airway button is greyed (or blacked) out on the last point of the SID, thus I'm not able to load an  airway at the end of the proc. I have to manually add the next waypoint and then load airway.

https://prnt.sc/137m8ld

If, instead of adding the next waypoint, I add the same fix than the last one of the SID, then of course I can load airways.

https://prnt.sc/137mbbv

But during flight (I think it's related to Vanilla FPL system), having twice the same fix in sequence will lead to a discrpancy between the flown leg by the AP, and the displayed current leg on the FPL Page, MFD and PFD. The leg between the two same fix is not skipped in the FPL, but of course is "skipped" or "flown" by AP.

https://prnt.sc/137ml5b

So I suppose there are two issues in there, the first one being linked to WT G3000, the second one probably a sim issue, but who knows :)

Thanks for any feedback ;)

**Comment by cywang90** [comment]
The sim's built in flight plan management system behaves strangely with consecutive duplicate waypoints, which is responsible for the behavior you saw when duplicating the last waypoint of the SID. Unfortunately there is no good way to work around this, since the behavior is inconsistent depending on a number of factors.

For now, the workaround is to avoid having consecutive legs with duplicate waypoints entirely (the one exception is that the first waypoint of the approach segment can be the same as the last waypoint of the enroute or arrival - this is because the sim treats the approach segment effectively as an entirely separate flight plan).

If you need to enter an airway from the last fix in a SID, you should just manually enter the next waypoint in the airway as the first leg of the enroute, then load the rest of the airway from there.

**Comment by RomeoMikeFox** [comment]
Alright, that's what I thought regarding duplicate fix on the FPL, that's fine. And so you confirm there are no ways that you are able to build the airway list from the last point of the SID?

I just would like to understand how it works behind the scenes, I have no doublt you would be able to do it if it was possible, of course. :)
Is SID treated a different way than en-route in the stock FPL system?

**Comment by cywang90** [comment]
Right now there's no way to load an airway directly from the last point of the SID in the g3000. You can do it in the g5000 using the flight plan keypad to directly enter an airway route following the SID.

The stock fpln system disallows any modifications to departures, arrivals, and approaches once they are set. This is different from the real units, which allow you to modify any part of the flight plan. However, the mod retains the stock limitations for compatibility purposes.

**Comment by RomeoMikeFox** [comment]
Makes sense thank you for your feedback Charles.
