### ISSUE TITLE
Longitude/G3000 Direct-to has incorrect active waypoints after reaching specified direct waypoint

### ISSUE THREAD

**Issue by Nerbulus** [Working-Title-MSFS-Mods/fspackages#1190]
So I was doing KMIA-TNCM in the Longitude/G3000
Flightplan route: MIA-SKIPS2.SKIPS RENAH Y355 SLUGO DCT ULUBA1 TNCM
The ULUBA1 leads into the RNAV 10 approach, and the RNAV 10 starts with the waypoint AVAKI as the final approach fix.
After I did direct-to AVAKI, the magenta line showed up and the plane followed it, but as I reached AVAKI the magenta disappeared and the active waypoints switched from DCT-AVAKI to an enroute waypoint-beginning of arrival. The plane didn't change nav heading, but the active waypoints were not correct. Would be appreciated if the direct-to behavior could be looked into.

**Comment by DctLamox3000** [comment]
I get this even without a DCT,
The Longitude follows the correct LNAV path, but the magenta line and active waypoint don't update correctly.
Doesn't matter if sync is on or off. Started after SU4, and using v0.7.1

**Comment by Lysdestic** [comment]
I can confirm that I'm seeing the same behavior as DctLamox3000.

**Comment by cywang90** [comment]
For Nerbulus's original issue of direct to into an approach waypoint breaking further flight plan leg sequencing after reaching the direct to waypoint: that has to do with a base sim bug. Basically what happens is when you activate the direct to, if the approach had been activated, it gets deactivated. Then, when the direct to ends, the sim tries to figure out which flight plan leg it should activate based on the plane's current position, but because the approach is now deactivated, non-approach legs in the flight plan take precedence.

For this particular flight plan, several legs of the arrival almost perfectly overlap the approach legs after AVAKI, which is where the plane is located after the direct to ends, so the sim automatically selects one of the legs in the arrival. The workaround for this is to just manually activate the appropriate approach leg yourself.

**Comment by DctLamox3000** [comment]
Fine, but then I need to open a new issue. Because the behavior noted occurs all the time, even without any DCT, and only started with v0.7.1.
