### ISSUE TITLE
KIAG crashes  flight when trying to load charts

### ISSUE THREAD

**Issue by unique311** [Working-Title-MSFS-Mods/fspackages#1239]
KIAG freezes  flight sim when trying to load charts
I tried KDCA to see if it would freeze when I load a chart and it didnt.
While in VR..

update:
tried in in regular mode, nonvr., and it freezes when i load the KIAG Niagara Fall Intl charts

**Comment by cywang90** [comment]
The freeze was due to incorrectly formatted georeferencing data for the KIAG airport diagram chart. v0.7.3 includes a mitigation for this that prevents the freeze and should allow the chart to be displayed normally. However, be aware that the airplane icon will not show up on the chart, and this may not be resolved until Navigraph fixes the data on their end.
