### ISSUE TITLE
Altitude missing from flight plan

### ISSUE THREAD

**Issue by burke312** [Working-Title-MSFS-Mods/fspackages#1242]
After installing v0.7.2, I've lost all altitudes in flight plans when flying the Longitude.  All waypoint altitudes are missing, but if the Route and Waypoints navigation aid in the Assistance menu is enabled, the navigation icons display the altitude for the next waypoint. See attached screengrab. Thanks!

![Microsoft Flight Simulator Screenshot 2021 06 16 - 15 45 11 46](https://user-images.githubusercontent.com/86056303/122391232-671cf000-cf38-11eb-9a89-23e8778bbd91.png)

**Comment by billydragon** [comment]
G3000 on TBM930 have the same error. No more Altitute in FPL.

**Comment by cywang90** [comment]
This is intentional. The altitudes provided by the sim's flight plan are oftentimes incorrect, so they are ignored in order to not cause issues with the new advisory VNAV feature.

You must enter all altitude constraints manually. If you wish to view the published altitude constraints for procedure legs but don't have access to charts, you can load the procedure in the **standby flight plan**, which will display the published constraints for each leg.
