### ISSUE TITLE
Garmin G1000 NXI Autopilot Bug 

### ISSUE THREAD

**Issue by MarkC17** [Working-Title-MSFS-Mods/fspackages#1292]
Autopilot does not turn on when using G1000 in the TBM 930 on Xbox Series X.

**Comment by mattnischan** [comment]
@MarkC17 A few things. If this is regarding the G1000 NXi from the Marketplace, we are not accepting bug reports for that here, since that is not one of our open source mods (it's a brand new from scratch product). Feel free to leave feedback on our Discord, in the NXi channel.

However, I'm still a little confused, as the TBM 930 does not use the G1000 NXi. The TBM uses the Garmin G3000, which we do not have anything available for on XBox.
