### ISSUE TITLE
G1000-nxi causing sim to Freeze, does not recover

### ISSUE THREAD

**Issue by PingNZ198** [Working-Title-MSFS-Mods/fspackages#1304]
MSFS GUI freezes - no actions alter screen in any way.  Cannot ALT-F4,  mouse pointer not displayed when in screen.
Does not recover after waiting 5+ minutes.

Have flown flight plan below several times with nxi deleted & had no issues.
Have flown flight plan below several times with nxi installed & had freeze every time between WI and ZORBA.

MSFS: 1.18.14.0  (PC)
GARMIN G1000 NXI: 0.2.0
Community Folder: Empty
Rolling Cache active (Emptied since SU5 + HotFix 1 installed)
Dev Mode: Off

To reproduce:

A/C: Cessna 208B

From NZHN to NZAA
IFR (Low)
Dep: GOMU1P   Apr: RNAV 23L-S

Displaying both the glass cockpit windows  (PFD & MFD) during flight

Freeze consistently occurs between WI and ZORBA

**Comment by dga711** [comment]
Hey there. Since the NXI is not one of our projects on GitHub we don't accept reports here. Please head to our Discord or MSFS forums.
Besides that. Does it happen to you when not loading the flight plan from world map? 
There is not really something I can think of where the Avionics would make the sim freeze at a specific location.

**Comment by PingNZ198** [comment]
My apologies,  I followed the MSFS Forum suggestions and went to Discord.

The WT Anchor page on Discord states: 

**2)    Bug reports :face_with_monocle:  should be made here: https://github.com/Working-Title-MSFS-Mods/fspackages/issues | bugs reported on #discussion will likely be lost in the discussion and not addressed.**

I searched the WT Discord, but could not find any other reference to "Bug Reports" relating to nxi.  #nxi-early-access was full of so much off-topic material, it seemed highly likely that a bug report there would also get lost.

On that basis, I came to github and created the issue here.  I also put a mention of having done so in #nxi-early-access. 


I have not yet tried to test this issue with a flight plan entered in the nxi, only from the World Map.

As the problem became absolutely reproducible on my system, I thought WT would value the report and my efforts.

I spent 2 days tracking down this issue, involving numerous single config changes, freezes, waiting to be certain it is not a "temporary freeze", restarts of MSFS, Reboot of PC etc.  I was also very surprized to find it was WT code that seemed to be involved in the issue and made multiple attempts to prove/disprove that assertion.

From my 48yrs commercial and voluntary software development background, I would guess that something in NXI 0.2.0 has locked up the main thread so tightly that the windows message pump is not handling any messages. So Timers, Keystrokes, mouse, Alt-F4, window activity etc etc etc all freeze, permanently.

I have previously used Zendesk to report MSFS issues, in spite of the time it takes to research, prepare and submit issues and (apart from an automated acknowledgement) have received no feedback or, in most cases, a fix. I will shortly be "sending" birthday cards to some zendesk issues (e.g. radio tower in middle of NZOU runway). As MS/Asobo obviously value my voluntary efforts so little, I will not submit issues to ZenDesk as the effort and frustration are just not worth it.

Best Wishes.

**Comment by dga711** [comment]
All good. We surely didn't update all our info pages on how the feedback flow on the NXI should work.

We value feedback and these reports highly and try to follow up on all of them. But sometimes we can't catch them all.
As I offered in Discord, if you feel like you got a reproducible case for a major issue and we miss it, feel free to ping one of us.

For Zendesk I can tell you that every issue gets looked at and if feasible and reproducible it ends up in the backlog and is prioritized. 
While communication can always be improved it is a monumental task to engage with people on the amount of reports that are received daily. But be assured, everything is being looked at. 

-----------

So to your specific issue. I just tried the flight myself and sadly can't reproduce issue. Trust me, I would love to have it crash, so we can fix it ;) Which is not to say the issue doesn't happen, but I can't reproduce it right this moment.
Like with the other reports, it can be very specific cases with specific configurations and content on different systems.

One thing I can imagine is that something like the flight path calculation might end up in a loop and therefore locking the sim. So we will stay aware of that.
In the meantime we also already changed a lot of code again, so maybe the issue is already resolved internally.

My suggestion would be, that we still keep an eye out for these kind of reports and try to reproduce. And on the other side there will be another update very soon and I look forward to you reporting back how it goes.

Thank you!
