### ISSUE TITLE
G1000 mod for FS2020 suggestions/fixes?

### ISSUE THREAD

**Issue by srmudry** [Working-Title-MSFS-Mods/fspackages#1308]
Just flew a flight after installing the update to the G1000 mod in the FS store.
1. Shouldn't the sky be a different color than the water?  Flying over the ocean results in a confusing display.
2. The right panel of the G1000: I think the compass 'rose' should encompass more of the display, not just the center.
3. ATC: may not be a G1000 problem but... ATC complained about not holding altitude even though the aircraft (Bonanza G36) showed the requested altitude and had the baro pressure set to the ATCs designated value.

**Comment by dga711** [comment]
Hey there. Thanks for your feedback. The NXI is not part of our projects on GitHub, so we don't accept reports here. Please head to the Discord or the thread in the MSFS forums.
Still.... 
1: Probably right. Will log as a bug and look into it. Thanks
2: You mean the ARC? Should be alright according to the trainer
![image](https://user-images.githubusercontent.com/2995606/128312874-ca84787f-3395-4180-8642-1116302c1437.png)
3: You might be victim of the altimeter bug in the sim, which will be fixed in the coming MSFS Hotfix https://forums.flightsimulator.com/t/regarding-your-feedback-upcoming-hotfix/436063?u=dga711
