### ISSUE TITLE
G3000 - Airports in double since SU 5

### ISSUE THREAD

**Issue by TingMei23** [Working-Title-MSFS-Mods/fspackages#1311]
Hello,

Seem SU 5, each airport is in double in the G3000 wich seem at the moment just a display problem, but i also note since i often have a message on the garmin about Synchronization problems.

Any idea ?

**Comment by gordongreig1966** [comment]
I have this issue too, although slightly more than a display problem, because when using the waypoint database, I can no longer see the airport ILS frequencies. I've confirmed it is a WT G3000 issue - uninstalling the mod removes the duplicates and I can see the frequencies again. Note that this is when I have Navigraph data + charts installed. With Navigraph data only, no issues.

Having experimented a lot with this, I think the issue may (oddly) be the order of installation.

1. With no Navigraph data installed at all I installed the WT G3000 mod, ran the sim and got no duplicate data.

2. I then installed the Navigraph data + charts  + CRJ data - ran the sim and got duplicates

3. I removed the CRJ data - still duplicates

4. I removed the charts data - still dupliactes

5. I removed all Navigraph data - still duplicates

6. I removed the WT G3000 mod - no duplicates this time

7. I installed the Navigraph data, no charts - no duplicates

8. I isntalled the Navigraph data + charts - no duplicates

9. I installeed the WT G3000 - still no duplicates

10. I installed the CRJ data - still no duplicates

So now I have all the data and the WT G3000 installed and no duplicates - ecatly the same state as at step 2, but I got there in a different order. Which is a bit weird. It looks like I need to install the Navigraph data withut the G3000 mod, run the sim, and then install the G3000 mod.

Hope this helps somehow

**Comment by mattnischan** [comment]
Hi all,

Unfortunately this is a sim issue introduced in SU5 and as such we cannot address it with the mod. The issue has been logged with the MSFS team.
