### ISSUE TITLE
CJ4: FMC issues with some pages (V0.3.0)

### ISSUE THREAD

**Issue by Jack737800** [Working-Title-MSFS-Mods/fspackages#132]
Just want to let you know, what if´ve seen so far (maybe this is also already known!?)

POS INIT:      AIRPORT ID, not able to fill in

T/O REF:       when entering rwy surface winds on page 1, page 2 get´s black (either way - next page/ or prev. page)

DEP/ARR:     Arrival - after selecting type of approach, in my case at EDDK for RWY 14L, DEPOK Trans. is automatically loaded into
                    the trans and I can´t "de-select", or delete it.
                    I also could not see any missed approach procedures after loading the type of approach beeing loaded into the legs
                    page.

ACT FLPN:    When entering the first waypoint into TO it won´t get displayed on the second page, neither the selected SID

LEGS:           FMC is creating user waypoints USR (my case WYP5F SID out of EDDK) first point is USR with runway heading of
                   137° which is good to me, but the point is displaced and not located in the actual runway heading flight path, thus
                   leads into a false indication of the FD

**Comment by K20017** [comment]
1) What airport identifier are you trying to input into POS INIT?

2) Did you have a departure runway loaded in?  It will currently crash if you don't since it doesn't know the runway heading to calculate winds

3) This is a problem with Asobo's database, you can't seem to select transitions.  We are investigating.

4 & 5)FLPN and legs page issues are currently being worked on.  There are also problems with the database not having the correct fixes/missing some, etc...

**Comment by Jack737800** [comment]
1. Flying out of EDDK

2. Correct, after I had selected in the DEP/ARR the runway 14L, it was added to the T/O page 1 as well and now T/O 2 is available
    again. Seems that I need to enter "rw" upfront the designator (14L) so that the system recognize it. (sorry...I´m flying on
    universal FMS, which works a bit different.

3. Perfect !

4&5: Outstanding job so far guys! Thanks for your effort to make this baby great again ;)

**Comment by K20017** [comment]
For some reason, the database for certain European airports is jacked up.  One of our team members working on the G1000 is having a hell of a time trying to draw out the proper approach fixes for this one approach out EGLL because it's not correctly identified in the database.  I just loaded up EDDK and 14L just fine.  Are you pressing EXEC after inputting the runway?

**Comment by Jack737800** [comment]
I see, what a pitty....
Yes, of course I did

**Comment by K20017** [comment]
Yes, very funky stuff going on.  The database is a big issue tied to many things right now.

**Comment by dga711** [comment]
@Jack737800 DEP/ARR should be fixed in v0.3.1

**Comment by Jack737800** [comment]
Sweet, will give it a try later on ;)

Thanks for taking care

**Comment by mattnischan** [comment]
@Jack737800 - For your item relating to being unable to see the first fix on FPLN page 2, the first fix is actually displayed on FPLN page 1. This is indeed how it is on the real ProLine, there's one input line for the flight plan on the first page.

**Comment by cwburnett** [comment]
this should all be resolved for 0.5.0
