### ISSUE TITLE
Annunciation Messages won't work on Turboprobs

### ISSUE THREAD

**Issue by magraina** [Working-Title-MSFS-Mods/fspackages#1325]
This is a bug which appears on Vanilla, WT G1000 0.4 and on the NXi

The problem is caused by a function which only allows a engine type which is equal to pistons. 

Before SU5 I fixed this by my self in the file
workingtitle-g1000\html_ui\WorkingTitle\Pages\VCockpit\Instruments\NavSystems\Shared\CommonPFD_MFD.js

```
if (this.engineType == EngineType.ENGINE_TYPE_PISTON) {
```
to

```
if ((this.engineType == EngineType.ENGINE_TYPE_PISTON) || (this.engineType == EngineType.ENGINE_TYPE_TURBOPROP)) {
```

Now with SU5 this will not work anymore.
The only way I found out is to change the file from the game itself, which has the same wrong function.

**Comment by mattnischan** [comment]
@magraina The NXi is not a mod and doesn't use any code from the original unit. Are you certain you do not get annunciations? I seem to get them in the Grand Caravan.

As far as the other fix goes, the legacy WT G1000 mod is simply the stock G1000 + the extra engine pages as of 0.4.0. We will not be expanding the scope of it as we are focusing on the NXi.

**Comment by magraina** [comment]
@mattnischan 
I've done the improvement mod for the Cessna Grand Caravan from beginning and this is a bug which was ever there.
I've created many new annunciation messages for this aircraft.

I only get Annunciation messages in the NXi if I correct this issue in the original source. So the NXi seems too be using some original source. Also the WT G1000 v0.4 version does that since SU5.
So something has changed or this is a bug, which maybe should not be there.
I noticed that cause I tried to fixed that as normal and it didn't work.
It cost me a lot of time to figure out, that I could fix this with the original source. I fixed that by accident.

For me it is a easy thing, cause I only need to correct one file, for every G1000 version.
It would be cool, if I don't need to fix that.

**Comment by mattnischan** [comment]
> Also the WT G1000 v0.4 version does that since SU5.
That is correct, because it no longer ships any modded files except for the engine pages. The CommonPFD_MFD.js from the game is what will be used.

> I only get Annunciation messages in the NXi if I correct this issue in the original source. So the NXi seems too be using some original source.

I would doublecheck that you're actually using the NXi. We don't reference, use, or otherwise bundle CommonPFD_MFD.js, nor do we use any of the code in any way from the PFD_Annunciations class. I have confirmed with the Coherent debugger that CommonPFD_MFD.js is not loaded at all into the PFD or MFD pages, just in case. If you would like to validate that you have the correct stuff loaded, I would use the Coherent debugger to debug the NXi PFD. It should almost entirely consist of one large pfd.js file. The CAS display is contained in the classes `CAS` and `CASAnnunciation`.

**Comment by magraina** [comment]
> I would doublecheck that you're actually using the NXi

I've doublechecked it again and you're right. I don't know why they wasn't there when I had tried that at the first time.
I cannot reproduce that

> That is correct, because it no longer ships any modded files except for the engine pages. The CommonPFD_MFD.js from the game is what will be used.

Okay that explains a lot. So this issue can be closed
