### ISSUE TITLE
g3000-v0.7.4a issue when I turn the battery ON

### ISSUE THREAD

**Issue by mmoda81** [Working-Title-MSFS-Mods/fspackages#1326]
The new version of the G3000 makes my TBM CTD when I turn the battery ON. Always when I restart a second flight or exit the simulator and come back later. It has worked here if I remove the mod and reinstall again.

**Comment by TingMei23** [comment]
I have the exact same issue. I didn't try un uninstall/reinstall, i just need to relaunch the sim and hope i will not CTD when BAT ON. Is someone find a solution about this ...

**Comment by meitemar** [comment]
This happens with me as well when I use the G3000 mod together with the TBM improvement mod.

Copy pasted from msfs forum where I posted: 
"No other mods than the TBM improvement mod and the WT G3000 in the community folder.
Only default liveries, and latest versions of the mods.
Clean install of the game. Decent hardware. No other issues.
Deleted and rebuilt the content.xml file.
Flying in Norway.

It happens every time I switch on the battery first thing from cold and dark (CTD). Though I managed to avoid it by flipping switches and turning knobs at random before turning on the battery a few times like someone suggested. Very inconsistent.

Since I am not the only one with this issue, Im guessing it has something to do with those two mods together."

**Comment by TingMei23** [comment]
I have found a solution for this.

Launch the flight, and when loaded, wait 15 seconds before to click on the "Ready to fly".

I never had the problem since.

**Comment by BernhardFelber** [comment]
I have the same issue. Always CTD when starting the batteries on the TBM. Only WT G3000 mod in community folder. Waiting before clicking Ready to fly did not help either. Would be nice to have a solution for that since I really enjoyed the g3000 mod in the TBM.

**Comment by HeliSteveNZ** [comment]
Yep, I also have the issue at some airports when turning on the battery. Very frustrated that no one has found a solution.

**Comment by mattnischan** [comment]
Hi all,

As JavaScript instruments like the G3000 cannot CTD the sim unless there is an underlying bug in the sim (just like JavaScript cannot crash your browser unless there is a bug in the browser), this issue is not addressable on the mod end.

Additionally, the mod is in maintenance and compatibility only as all G3000 effort will be out towards the eventual G3000 refresh in the  Marketplace. However, the MSFS team is fixing CTDs frequently, so it is possible that they will also be able to fix this one as well before then.
