### ISSUE TITLE
CJ4 CTD

### ISSUE THREAD

**Issue by 39crauds33** [Working-Title-MSFS-Mods/fspackages#1352]
Nothing else in community folder except CJ4 latest mod and G3000 latest mod.  Still CTD every flight either when reaching altitude or when beginning descent.  Event log shows nothing.  No other aircraft has CTD with mod G3000.  WX and AI traffic eliminated as an issue.  I have I7-7700 4.5Ghz and 1080ti 16 Gb memory.  Nothing overtaxed during flight.  GPU Temp normal and all CPU cores evenly used. Nothing spiking.  Memory only 65% being used.  I have no cache, but 100 mps download speed, no stutters, high frame rates.  Several different flights with the same issue.  Cannot complete a flight with CJ4.  Longitude, TBM 930 = no issues

**Comment by TomL7753** [comment]
I confirm the issue. Nothing in Community folder except CJ4 latest version. WX and Traffic eliminated as well, updated Nvidia Driver, reverted overclocking - still CTD on every flight, but a bit random: sometimes it happens on taxiing out, sometimes in flight, sometimes on approach. Tried the same route with the TBM and G3000 mod - no CTD. Flights >2 hours with the TBM are without CTD. It started with SU5. I am under the impression that it has something to do with the flightplan management, as "free flights" without FPL in the FMS don't crash (although they tend to be shorter)

**Comment by higorgig** [comment]
Same here. I tried 3 flights today with the CJ4. No live traffic, only the CJ4, a livery (N325CJ) and the navigraph AIRAC 2108 at the community folder.
The first flight it crashed to desktop when I started taxi. The others during climb and cruise phase.

**Comment by higorgig** [comment]
@mattnischan you're right. I tried a different route, flight level, no navigraph, no simbrief linked, no live traffic and I have CTD still. No problems flying another aircraft in the same route. There's something going on when the aircraft try to communicate with the sim. I hope it get fixed with the upcoming sim update.

**Comment by TomL7753** [comment]
I doubt it because I didn't see many CTD reports regarding the CJ4 and that would make it hard to find the cause for MS/ASOBO. I reported to Zendesk but only got generic answers and that it lies in the responsibility of the third party to fix issues - despite me reporting that Matt pointed to a sim issue.

**Comment by TomL7753** [comment]
As expected: WU6 didn't change the situation, CJ4 still CTD's randomly. Sad story. It was great as long as it lasted.

**Comment by higorgig** [comment]
Yes. Just had a CTD here with the CJ4. SU6.

**Comment by TomL7753** [comment]
According to a post in your Discord I deleted the content.xml file (and for safety reasons deleted the rolling cache), and was able to finish two flights since then, one of them 2:30 hrs long. So I guess it seems safe to assume the issue can be considered solved as it seems it was a Navigraph issue.

**Comment by 39crauds33** [comment]
Tried again after latest fix for SU6.  Used only CJ4 12.7 and working title G3000 v7.4A.  Flight climbed and cruised with insig Wx @ FL380.  Lasted 47 min and then CTD.  This was @ cruise flight with no traffic and nothing occurring except smooth level flight.  Again this was sudden and Event Viewer only states the crash of flightsimulator with no other details.  System is not overloaded or overheating.  Any suggestions or ideas?
