### ISSUE TITLE
G1000 NXI 0.9.0 map flicker

### ISSUE THREAD

**Issue by Humpix** [Working-Title-MSFS-Mods/fspackages#1430]
Hello, with version 0.9.0 there are problems with the map display (the right one, I think its called mfd?). After editing around a bit in the flight plan, I only see the water, but no topography anymore. This then flickers now and then or stop refreshing completely. The flight route (magenta line) remains and also works. If I turn up the display rate of the avionics in the graphics settings, it flickers faster. It looks like there is a problem with the rendering? Happend to me on every flight...

BR,
Mathias

**Comment by mattnischan** [comment]
Hello,

Since the G1000 NXi is not one of our open source mods, and instead a brand new product, we do not log issues for it via GitHub. Please visit us on our Discord or the FS Forums.

However, we are aware of the issue and should have a fix in the next update of the NXi. For now, you can workaround this issue by not changing to any of the WPT information pages via the FMS outer knob.
