### ISSUE TITLE
Battery or any Power ON CTD with G3000 mod

### ISSUE THREAD

**Issue by HeliSteveNZ** [Working-Title-MSFS-Mods/fspackages#1498]
I had this problem at some airfields/airports with v0.7.6 and v0.7.7 and thought I had it solved by removing Pilot2ATC's FSUIC software. All was good when I tested it, however, when I tried later in the day, the issue turned up again. The only other change was updating Navigraphs AIRAC Cycle. I have tried again with Navigraph removed from the Community folder but still CTD. I see that this has been an issue with many many people but with no real solution. Strange that this has not been resolved.

**Comment by mattnischan** [comment]
As JavaScript instruments like the G3000 cannot CTD the sim unless there is an underlying bug in the sim (just like JavaScript cannot crash your browser unless there is a bug in the browser), this issue is not addressable on the mod end.

Additionally, the mod is in maintenance and compatibility only as all G3000 effort will be out towards the eventual G3000 refresh in the  Marketplace. However, the MSFS team is fixing CTDs frequently, so it is possible that they will also be able to fix the issue before that time.
