### ISSUE TITLE
G1000 file size

### ISSUE THREAD

**Issue by patirish2** [Working-Title-MSFS-Mods/fspackages#154]
[Working Title G1000 error.pdf](https://github.com/Working-Title-MSFS-Mods/fspackages/files/5308022/Working.Title.G1000.error.pdf)
I get this file size error when I placed the g1000 file in my community folder
Pat

**Comment by mattnischan** [comment]
@patirish2 

We don't have any control over where we can place the files within the package folder, as they must match the layout of the Asobo files and folders in order to overwrite and modify them. Windows has, by default, a 260 character limit on path names. However, you can disable that limit in Windows (there are some guides out there; I won't link them as some involve registry edits) or you can move your MSFS packages folder to a less nested location on your disk.

For example, my folder is at G:\FlightSimPackage\ partially to avoid this issue.

**Comment by kaosfere** [comment]
I have this problem myself.     My full Community folder path is `D:\WpSystem\S-1-5-21-1592962005-952208934-1148966161-1001\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community`.    

I have solved this by creating a directory junction with the `mklink` command:

`mklink /j d:\Community d:\WpSystem\S-1-5-21-1592962005-952208934-1148966161-1001\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community`

Then you can just install stuff into `d:\Community` and things are happier.

As Matt said, this isn't a G1000 issue so I'll close this, but hopefully those instructions help.

**Comment by patirish2** [comment]
I decided to do a complete reinstall. I put the files in a short folder on D: and now (about 7 hours later) the add-ons work great.

 

Thanks very much for your suggestions.

 

Pat

**Comment by patirish2** [comment]
Thanks.  I reinstalled and put the files in a short folder like you did.

 

Pat
