### ISSUE TITLE
CJ4 Oscillation in flight

### ISSUE THREAD

**Issue by triplesevenbob** [Working-Title-MSFS-Mods/fspackages#163]
CJ4 mod 0.3.1 version oscillation in all phases of flight. May be at lighter loads did only 2 quick flights. with no pax, 1 pilot, and a large amount of fuel. Plane oscillates on autopilot in climb, cruise and descent, up and down pitching like a roller coaster. Wind at higher levels around 60kts tailwind.

**Comment by mattnischan** [comment]
@triplesevenbob - This appears to have been introduced with the autopilot changes in 1.9.3. We attempted to tune the autopilot PIDs in 0.3.1 but were unable to reduce the oscillations. There are reports of this on the stock aircraft as well, and it seems to me like the issue is inside the sim code itself, and not the aircraft code (which is all we can access).

I'll leave this open until the next MSFS version and we'll see if it improves.

**Comment by Jack737800** [comment]
I´m using the V/S mode only so far and I do not have this oscillation :) but what I have, is again a little change "wish" to the autopilot system, when enabeling the V/S mode. (should I open a new issue?)

**Comment by edmond1992** [comment]
I do have the same issue, but it gone after I decent to FL260(more less)

**Comment by linxord** [comment]
The oscillations are a pain. I just flew over 800nm by hand. Decreasing altitude helps for sure. <FL300 is usually ok. I hope this gets fixed soon. I'm going around the world in this CJ4.

**Comment by dga711** [comment]
Should be much improved with the upcoming 0.4.1 patch.
Keep in mind. Much of it is Asobo's broken AP
