### ISSUE TITLE
CJ4 0.3.1 Can't enter the airport ICAO on POS INIT page

### ISSUE THREAD

**Issue by yusufsan38** [Working-Title-MSFS-Mods/fspackages#165]
When POS INIT page comes up after start to enter the current Airport that I parked at. I can't enter the ICAO code of the airport. It's displayed after the RTE page departure and destination is entered.

**Comment by Jack737800** [comment]
Having the same, but I got told this may have something to do which some European airports...

**Comment by cwburnett** [comment]
@Jack737800 @yusufsan38 on this FMS, the AIRPORT line is not a user entry line. It is auto-populated by the FMS based on the coordinates. We are working on an enhancement to do this without first having to set an origin.
You can enter a PILOT REF/WPT and copy that position into the SET POS field, however it has no impact on the simulation because the sim always uses actual LAT/LON in the sim for the FMS regardless of what is set in this page.
So we will be looking to add the auto-population of the airport, but know that in real world ops, all that is ever done is copying the GPS position into the SET POS field. Hope that makes sense.

**Comment by Jack737800** [comment]
It does make sense...Thanks for the more detailed information! Funny how different these systems are working, right?
On the Universal UNS it´s done if a different way
