### ISSUE TITLE
CJ4: Battery life (wish?)

### ISSUE THREAD

**Issue by Jack737800** [Working-Title-MSFS-Mods/fspackages#172]
Well, this seems nothing only to be related to the CJ, more to all planes from the new MSFS.

Maybe this is more like a wish, but do you see there any chance to extend to battery life?
I´m doing my normal preparation and after about 10 min. I get an "low voltage" amber light...The battery should last least about 30 min and still be able to operate the starter for the engine.

**Comment by mattnischan** [comment]
@Jack737800, our resident CJ4 pilot informs me that the real battery has about 10 minutes of life with the avionics on. In the real plane, you have the option to switch the avionics to `dispatch` with the battery switch off, which would give you more extended life as it powers far fewer modules and is meant for when you're inputting FMC data.

We have not yet implemented that feature as MSFS doesn't really have the concept of power unless the battery master is on, so there's some very deep custom work that will need to be done, and is probably fairly low on the priority list due to complexity. In the interim, I'd recommend starting the engines earlier in the process as a workaround to keep the batteries charged.

**Comment by Jack737800** [comment]
One more time glad that I´m not flying a CJ in real life :P (just kidding)

That´s exactly what I´m doing, this was just a "wish" or somthing I noticed within the sim!
I have no idea about programming, so I have no clue how easy, or difficult it is to change something like that, but I´m glad to hear that you trying to implent the mentioned "dispatch" function for saving the batteries.

**Comment by J-Hoskin** [comment]
@Jack737800 Thanks Jack for suggesting this. Extending battery functionality and adding a more realistic startup is on our todo list so I will close this issue.
