### ISSUE TITLE
CJ4 PFD completely frozen on approach on second leg in a raw

### ISSUE THREAD

**Issue by ygascard** [Working-Title-MSFS-Mods/fspackages#196]
Hi everyone,
Yesterday I tried the latest 0.3.1 with 1.9.3. Had the oscillation problem but it's another topic.
I first did a 2 hour leg without any issues, then loaded a FP and was gone on my second leg (about an hour and a half) on approach, I selected the approach, no problem and then wanted to change the altimeter settings and it was at that time that I saw my PFD completely freezed. Nothing was changing only the MFD and auxiliary instrument was working. Tried cutting off the avionics and back on and they were restarting with correct current values but frozen again. Had to find my way down manual flying with the MFD map and auxiliary gauge which was fun and quite stressful... ;)
I'm posing this here as I got this only now that I use this mod so....

Thanks for all your work!

**Comment by mattnischan** [comment]
Hi @ygascard,

We're pretty sure you got bitten by #190, which should be fixed in the next release. Sometimes the game returns DME distance as strings instead of numbers, which we weren't handling, and that would cause the PFD and MFD to crash if you had selected those locs or vors to be the displayed information.

Hopefully the next release will clear this up for you! Thanks for the report, we really appreciate it.
