### ISSUE TITLE
G1000 knob brightness

### ISSUE THREAD

**Issue by jonasbeaver** [Working-Title-MSFS-Mods/fspackages#22]
The softkey lights, and the lights around range, crs-baro, nav, hdg can all be lowered with the same menu key or rheostat (in airplanes with brightness knobs) in the real G1000.

In the picture you can see the instrument light knob in the DA62 1 tick above off, and in the menu they are both turned to 0% but the knob brightness is still 100%.
![image](https://user-images.githubusercontent.com/70987366/92551856-c40aad80-f224-11ea-958d-34521d394f25.png)

**Comment by CkovMk** [comment]
Set the "<EMISSIVE_CODE>" label to 0.5 may help. Here's my result:
Instrument Light Off:
![image](https://user-images.githubusercontent.com/29831136/92979402-21bd2500-f4c5-11ea-898b-6444525774e1.png)
One Click:
![image](https://user-images.githubusercontent.com/29831136/92979413-2e417d80-f4c5-11ea-81b8-e9fb1de54bc5.png)
Full On:
![image](https://user-images.githubusercontent.com/29831136/92979430-3994a900-f4c5-11ea-8b4b-42d5bb20ce68.png)

I notice that G1000 emissive light won't turn completely off, but this is the best I can get so far.
hope this is helpful.

**Comment by kaosfere** [comment]
Working on this one now.   The manuals I have show that the key brightness can be controlled separately from the display brightness as two different items in the PFD setup menu.   But I'm going to keep them tied to one item, because I think this is an area where ease of use trumps verisimilitude.   Especially since you can't save settings, no one's going to want to twiddle _two_ menu items for each screen to set the brightness every time they start the plane.

I have the MID tied to the MFD where there's no joint knob for it, as that seems to be how it's done in at least the DA40.
