### ISSUE TITLE
G1000: Transponder GND (Ground Mode)

### ISSUE THREAD

**Issue by bachian** [Working-Title-MSFS-Mods/fspackages#240]
I suggest the implementation of the GND like the real unit.

ALT mode should enter automatically when airborne. I believe it is activated when above 30kt (still need to confirm the exactly speed).

<img width="402" alt="gnd" src="https://user-images.githubusercontent.com/29262832/95698992-b6788700-0c19-11eb-8000-0d927f6dd44f.png">

**Comment by knighty** [comment]
I actually did the ALT automatic activation earlier today (does it at 50kts, if you could confirm a definite value that'd be excellent). Haven't got around to GND yet. Sounds like GND doesn't really do anything for us in the sim? I'm wondering if it's implemented internally at all otherwise I can probably work around it on a pure visual level

**Comment by bachian** [comment]
I'll try to find out the correct speed the ALT mode is activated. Good to know you already worked on that.

Regarding the GND mode, you are correct, it doest not make much difference for the simulator, but it is the mode we use most on the real plane. 

My suggestion is to implement the mode visually, with the same funcionality of the STBY mode.

Here is how it should appear:

<img width="935" alt="gnd" src="https://user-images.githubusercontent.com/29262832/95700114-9e563700-0c1c-11eb-8c8e-55c52e27a4c3.png">
