### ISSUE TITLE
CJ4: No Flashlight in Cold & Dark Cockpit

### ISSUE THREAD

**Issue by OliveBeast20441** [Working-Title-MSFS-Mods/fspackages#309]
First off, thank you for continuing to develop and modify this aircraft. All of the changes so far have resulted in a much more stable flying model. The climb out to altitude with Version 0.5.0 was flawless, with no porpoising or other issues, other than a reluctance to switch from IAS to MACH mode and adjust pitch to remain on the mach number setting, but that may be a sim issue, out of your control.

However, one feature that existed with the base model was the availability of a "flashlight" (for lack of a better word) when in the cockpit at night time. You could at least turn on the batteries and avionic switches, as well as the overhead rotary knobs before starting the main engines. Now it's completely dark and I find myself fishing for a tool tip or other means to light up the interior.

But never the less, many thanks for bringing this aircraft up to snuff!

**Comment by dga711** [comment]
@OliveBeast20441  To me it also doesn't turn on automatically right now. But I cannot think about somehing we do, that would cause this 🤔 
But you can turn on the flashlight via ALT + L hotkey. Or check the mapping in your control settings.

**Comment by cwburnett** [comment]
This issue is tied to the cabin lights. We're adding the feature to save the cabin lights settings. In the upcoming patch, the flashlight only comes on automatically if there are no lights on in the aircraft. However, if the cabin lights are set to be on because they're saved that way, ALT-L will have to be pressed to turn on the flashlight. If they're set to off at the end of a flight and saved that way, then at the beginning of the next flight, the flashlight would automatically come on if dark. Hope that makes sense.
