### ISSUE TITLE
[CJ4] Performance

### ISSUE THREAD

**Issue by DanP77** [Working-Title-MSFS-Mods/fspackages#362]
Not sure, but may be a excessive loss of performance increasing the altitude

**Comment by K20017** [comment]
Can you expand on this?  I can only assume that you were climbing at too low of an airspeed so when you get to higher altitudes, you were behind the power curve and could not increase speed.  I would suggest to climb at 240kts and transition to mach .64 at around 28-29,000 feet.  If that doesn't help, could you provide more information so we can figure out what is wrong because the high altitude performance looks fine for me.

**Comment by DanP77** [comment]
Which is the correct settings of N1 for the climb?

**Comment by K20017** [comment]
Varies due to altitude and temperature but in the real world, it's automatically controlled by the engine's FADEC.  But to simplify things, expect 93-97% n1 for climb and go max throttle at around 30,000.

**Comment by DanP77** [comment]
In this case it's ok also forme me.
So do we have to ignore the throttle levers position ?

**Comment by K20017** [comment]
For now yes because you would normally click the throttles into a climb and takeoff detent and FADEC controls the engine output but we can't simulate that right now and are thinking of some alternatives.
