### ISSUE TITLE
MACH Mode FLC

### ISSUE THREAD

**Issue by zainsyedz** [Working-Title-MSFS-Mods/fspackages#410]
On v0.6.0, in mach mode FLC, the speed in knots is maintained and not the mach speed..

**Comment by Danice737** [comment]
I Believe after some testing and watching the FLC mode in a Aircraft with a Autothrottle - the base AP code uses some throttle to maintain the climb near the capture speed. And since the Cj4 doesn't responsed to the throttle input from the AP it just creeps away from target speed. Doing some more testing and searching the base code for the block controlling the FLC climb

**Comment by cwburnett** [comment]
Closed to combine with https://github.com/Working-Title-MSFS-Mods/fspackages/issues/326
