### ISSUE TITLE
CJ4 - Disappearing and reappearing approach ALT constraints in FMS

### ISSUE THREAD

**Issue by dihedral977** [Working-Title-MSFS-Mods/fspackages#429]
Pics are in sequence to my RNAV approach into KASE. Prior to pic #1 all constraints were present. Pics 2-4 show gradual repopulating as I fly to each waypoint. Note, this happened twice on same approach in two different flights .  Am using navigraph BETA. Will report any similar behavior at other airports and/or other approaches. 

![1](https://user-images.githubusercontent.com/73390710/97307469-1dab5380-1836-11eb-93a9-8d16da6c02ee.PNG)
![2](https://user-images.githubusercontent.com/73390710/97307474-1f751700-1836-11eb-9328-0de5bd790053.PNG)
![3](https://user-images.githubusercontent.com/73390710/97307479-213eda80-1836-11eb-9a78-0180c0a68d19.PNG)
![4](https://user-images.githubusercontent.com/73390710/97307485-23a13480-1836-11eb-841a-b7e22a5a08df.PNG)

**Comment by dihedral977** [comment]
Is this a known bug? Anyone else experiencing this? Additionally, sometimes either the speed or alt restriction will disappear independently of each other.

**Comment by dga711** [comment]
I didn't see that yet. Will poke @cwburnett

**Comment by dihedral977** [comment]
Here is an example of partial constraints
![jovem](https://user-images.githubusercontent.com/73390710/97418526-49cedf00-18df-11eb-9f09-6ac0f47a9e45.PNG)
![jovem2](https://user-images.githubusercontent.com/73390710/97418535-4cc9cf80-18df-11eb-8e5a-4950195d929b.PNG)

 in the FMS on a STAR.

**Comment by dihedral977** [comment]
In this example, **some** of the constraints **are** shown on the PFD and MFD but not the FMS. JNGLE and QUBIT are the STAR and JAAJJ  and BAZAR are the RNAV Z 08L approach.  

![discrep](https://user-images.githubusercontent.com/73390710/97484994-e5883b80-192f-11eb-9523-5ba1cbb403c7.PNG)

**Comment by cwburnett** [comment]
So this is interesting. There are a couple things going on here. First, I changed the code on the LEGS page, but not the mapinstrument, so those constraints are the incorrect 'guessed' constraints. The LEGS page is pulling the correct data when there are actual constraints. Speed constraints are all wrong from what I can tell in the data itself, or I don't know where they're being pulled from.
On the LEGS page, the disappearing constraints is probably related to how I'm pre-loading the constraint data for the approach, but it may not be updating (or may be slow in updating?).
This will ALL go away with the new flight plan manager, so I'd probably err on the side of not spending more time on it since that is only a week or so out, but it would be interesting to look at the approach above and see if there IS data for GLOKK and LAYMN that isn't coming over...

**Comment by dihedral977** [comment]
I know you've put this on hold. I don't know if you're still interested in more or different examples. 

This one is different in that not only have either the speed and/or altitude constraints disappeared, but multiple waypoints vanished as well in the FMS but are **still shown** on the maps. The pic shows HDG mode but that was because I had to revert to it to stay on course. I was flying the WNGNT WNGNT2 STAR to ILS 03R @ KDTW. 

Let me know if you're still interested in more examples or not. 

![lost em all](https://user-images.githubusercontent.com/73390710/97702467-686eda80-1a85-11eb-97b7-65fa20ed006d.PNG)
