### ISSUE TITLE
More realistic engine behavior/fuel flow

### ISSUE THREAD

**Issue by wizzlebippi** [Working-Title-MSFS-Mods/fspackages#448]
Right now, it appears that fuel flow decreases with ambient pressure.  Fuel flow (and thrust) are actually dependent on dynamic pressure, which is why flying at high Mach/low airspeed is how airliners like to operate.  Ambient pressure still plays a part, but it is very much a secondary effect.  

Another fun fact that is less critical to capture is that the FADEC should either have a target N1 in mind, or should be trying to maintain an idle N2.  Because of this, if you increase the throttle and allow the aircraft to accelerate, it should hold a constant N1 and as the fan unloads (just like a fixed pitch prop) N2 and fuel flow will decrease to keep the fan from accelerating.  Likewise, starting from a high speed, chop the throttles to idle and watch the engines hold the idle N2 and N1 will roll back.  The idle speed should increase with altitude as well. 

Lastly, and possibly more critically, is simulating bleed states.  CJ4 has bleed air heated wing and horizontal tail leading edges, so when anti-ice is selected, engine performance should suffer and fuel flow should increase.  I can't say I've messed with this too much so far, but this doesn't seem to be well implemented right now.  

I'm sure if given enough time to mess with the engines.cfg file I could figure this out, but I don't have much time right now and there doesn't appear to be any useful documentation.  I also recognize that much of this might be impossible with the current flight model.  So, I'm posting it here and hoping that someone with time can pick this up.  If someone has any idea how the 1D arrays in the engines.cfg file are organized, that would be a great help too.

**Comment by mattnischan** [comment]
Fuel flow is a complex topic of course, but at a basic level fuel flow is always going to be TSFC * Gross Thrust. Now, there is no generalized formula for how TSFC changes with altitude and Mach, but a number of sources point towards an increase in TSFC as Mach increases and we found a TSFC/Mach curve that produces the fuel flows observed at various operating points in the real aircraft. Right now, the fuel flows are consistent with the actual plane.

Because fuel flow is only dependent on gross thrust, and because gross thrust decreases with decreases in air density, then fuel flow will also decrease commensurate. Yes, dynamic pressure (the pressure observed by the engine inlet) will indeed increase with Mach, but this effect does not come close to balancing the effect from ambient pressure drop. On top of that, you do have ram drag effects that decrease net thrust as inlet speeds increase, leading to a decrease in observed fuel economy vs observed performance. Every engine has a different low point in those curves where it will be most efficient.

However, none of that at all is modeled in the current iteration of MSFS, so we're running our own fuel flow simulation and adjusting the fuel tank levels to match our flow instead of the calculated flow. MSFS does also not model any bleed systems or FADEC. We have yet to incorporate any kind of custom full engine model or FADEC, but it is on the list.

**Comment by dga711** [comment]
FADEC etc incoming with 0.8.0
