### ISSUE TITLE
[CJ4] Adding a waypoint to the end of the FP in cruise screws up the order

### ISSUE THREAD

**Issue by julianpoma** [Working-Title-MSFS-Mods/fspackages#555]
**_Steps to reproduce_**

Set up the following route

SAAR DABOT W20 SIS DIGET SARF

Take off normally.

While on climb, I select runway 22 at SARF as arrival (I don't think this matters). 

Manually insert the FSA VOR at the end of the FP, clicking on the dashes (---) after DIGET, on the LEGS page.

**_Result:_** 
The FSA VOR is inserted before DIGET -> **SIS FSA DIGET** 

![imagen](https://user-images.githubusercontent.com/19490445/99026344-850d1700-2549-11eb-821e-6c2eec42a482.png)

**_Expected:_** 
FP should be **SIS DIGET FSA**

**_Bonus:_** 
If I try to remove the **DIGET** waypoint using the CLR function, **FSA disappears**.

**Comment by realvitya** [comment]
Don't know if that helps to focus on the problem but I also see that even though the upper display it is trying to go to the previous waypoint while telling the correct waypoint name. The lower display shows the correct waypoint as well with the correct distance. (The upper display what the aircraft is flying shows the previous waypoint with intended waypoint name and distance of the previous waypoint.)

It's like the AP is flying the upper display plan and coordinate is not swapped while the name is indeed swapped. Hope I could help! 🙂 I usually experience this flaw when I try to change the approach because of weather situation. It messes up the whole thing and I end up flying HDG, then ILS or visual at the end.

**Comment by dga711** [comment]
Thank you for the feedback.
As we are in the process of reworking flight plan related things, I would put this issue on hold for now.

**Comment by dga711** [comment]
Should be fixed in 0.8.0 which is coming very soon
