### ISSUE TITLE
CJ4 - 0.8.0 - KMIA ILS 08R no GS intercept

### ISSUE THREAD

**Issue by qpHalcy0n** [Working-Title-MSFS-Mods/fspackages#615]
VNAV activated for entire flight. From arrival to approach phase, preselected altitude 200 (DH). Upon turning to final, when LOC was intercepted, activated APPR mode and switched NAV to LOC1. Was about 100ft low on activation, but GS constantly showed white and never went green. Aircraft continued to descend even past published restrictions.

**Comment by qpHalcy0n** [comment]
I should also mention this is with the most current Navigraph beta data.

**Comment by K20017** [comment]
Did you ever intercept the glideslope?  You said you were 100ft low and it continued descending.  Did you ever become high on the glideslope?

**Comment by slip664** [comment]
I was unable to replicate this. I did like you explained as close as I could but The AP intercepted the GS and followed it all the way down. For the future, that approach has baro minimums of 450'. The lightning bolt at the MAA is 1500' so that's the lowest you should ever have to set the altitude to. The autopilot will descend you down on an ILS past the altitude set in the window if it captures a glideslope.

**Comment by dga711** [comment]
No further information. Maybe improved with coming update. Closing for now.
