### ISSUE TITLE
TOD indicated in place of FL setted

### ISSUE THREAD

**Issue by jdeyrieux** [Working-Title-MSFS-Mods/fspackages#625]
after to add a FL to a waypoint, the plane is at this FL already, then TOD (green) is added to the MFD.
FL constraint expected.
![image](https://user-images.githubusercontent.com/1239376/102526651-457fa080-409c-11eb-83ff-666c78b03be5.png)

**Comment by K20017** [comment]
The CJ4 does not input any cruise altitude in the constraints or automatically fill in what the crossing altitude will be for every fix.  It only shows constraints for those pulled by the nav data or pilot input.  So you don't need to put FL420 in there.

**Comment by jdeyrieux** [comment]
I understand, my question was more precisely about : is TOD expected in this case ?

**Comment by K20017** [comment]
That's probably an erroneous value as it's probably not liking the strange FL420 constraint there.

**Comment by taguilo** [comment]
Hi,
Actually what should happen is, if you have an Arrival/Approach with altitude constraints loaded in the FMS, and you include another altitude constraint in, for example, a cruise waypoint, and VNAV is not able to comply (because descent should start before arriving at that wpt), then the constraint value should display in yellow; in this case with no further info to the pilot, who needs to figure out why the yellow color.

**Comment by cwburnett** [comment]
@jdeyrieux this is occurring because you have set the VNAV target altitude for your current altitude. Therefore, VNAV is determining when you'd need to begin a descent to reach FL420, which in this case is exactly the waypoint since you're already at that altitude. Remember that VNAV in this aircraft is for descent planning, not cruise altitudes, so it always takes the next constraint and evaluates when you need to begin a descent to reach that altitude at the specified flight path angle. Adding cruising altitudes as VNAV constraints will always yield this behavior.

**Comment by taguilo** [comment]
VNAV is both for descent and cruise. I smart detect when a wpt constraint is in the climb or the descent portion of the flight  plan. The destin is 655 miles ahead so it should have detected that.
Quoted from FMS3000 VNAV section:
__"The initial location of the TOD is at the intersection of the planned cruise altitude and the planned descent path."__
And
_"The aircraft is considered to be close to the descent path when it is 50 NM or 20 percent of the distance from origin to the
destination, whichever is smaller (but not less than 6 NM)."_

Hope this helps.

**Comment by jdeyrieux** [comment]
Thanks!
