### ISSUE TITLE
CJ4 - LNAV steering

### ISSUE THREAD

**Issue by TomL7753** [Working-Title-MSFS-Mods/fspackages#686]
Routing: LOWS15 DETS2B DETSA Y106 CHI Y664 IBRID IBRI1Q LIRQ05 

When reaching DETSA (end of SID!!!), the aircraft turned RIGHT instead of left to NIVAS. The LNAV bearing pointer (magenta needle) turned approx. >90° to the right before returning to the correct direction, I think that was causing the issue. I intervened with HDG mode, so unfortunately I don't know if the ac would have returned onto the track, although it seemed so.

Here's a link to a video of the incidence, it occurs at 0:22 : https://mega.nz/file/MQpgBZQa#ZonjxxxYlPvwLXcPGesf7dp1DMgx96PQpQl65hYP9M4

Please observe that this has happened before, see #650. In this instance, the ac definitely not returned on track. **In all instances this occured it was the end of the SID.**

**Comment by neoeinstein** [comment]
My guess is that this has more to do with the default MS autopilot which is very aggressive about getting to that magenta line. The FMS is moving to the next waypoint at the appropriate time, but then the MS autopilot decides it needs to get to the magenta line _faster_, so turns toward the line rather than keeping the bearing that would intercept the magenta line. This is also what results in the overshoot.

**Comment by cwburnett** [comment]
@TomL7753 In this case you had DETSA in the flight plan twice, causing the FMS to try and fly to the next waypoint. It starts a turn to the duplicate waypoint, which is now behind you, then realizes it should sequence to the next waypoint and starts to turn back. It was already correcting when you swapped to heading mode. Had you just not touched anything, you would have been brought right back on course just a few seconds after you switched to HDG. But, it is important to check your flight plan for duplicates, because FMS behavior will be unpredictable with dupes. Hope that helps.
