### ISSUE TITLE
CJ4     2 x CTD after T/O below 500 ft

### ISSUE THREAD

**Issue by Thaiger52** [Working-Title-MSFS-Mods/fspackages#699]
2 flights - all same conditions and flightroute
- installed mods: working title CJ4/G1000/G3000 and A32NX mod - EDIT: all mods with latest version after VR-Update MSFS
- route planning in worldmap and using FPLN RECALL - very short route, only one return point 60 nm out and in for RNAV, no problems with RECALL (VTUD30-LOY-RNAV VTUD12)
- CDT after T/O below 500 ft (sel. HDG-Mode/sel. VS 2500 /FD, still in T/O power, no AP/YD)

2 fligths - same conditions as the first 2 flights except:  **disabled all other working title mods and A32NX** -  except CJ4 of course
- no problems detected

Sorry, had no time to test which one of the other mods could lead to a possible conflict,  hope it helps a bit anyways.

despite: fantastic work and many many thanks ...

Merry Christmas and Happy New Year

**Comment by mikebakke** [comment]
I have just run multiple tests with CTDs while still in the SID. Currently way beyond that point after removing the WT G3000 mod from community. So far so good.... A nice Christmas present :-)

**Comment by cvitre23** [comment]
a CTD  just after TO, first time for me !! After several freeze of MSFS due (i think) to a bad airways number, i enter via game recall mode the route ..... works fine, but just afetr TO freeze ...CTD.
 I have several CTD (not so much before the last VR update of FS2020) since the V0.8.3, same with the G3000 (0.3.4) mod ...  freeze the PFD left & right after 1 hour of flight.

Hope this will help. Despite FANTASTIC job for all the mods , many thanks and Happy New Year to the team

Crash dump: https://gofile.io/d/6HQBkC

**Comment by reczyzewski** [comment]
I have also had multiple CTDs on departures in the CJ4 since the latest MSFS update using the v0.8.3 mod.  Last night I didn't even get off the runway.  I thought it was possibly related to the release, but I haven't had any CTDs with any other aircraft.  Will try to gather a bit more information to help with the diagnostics.
