### ISSUE TITLE
Repo Restructure

### ISSUE THREAD

**Issue by J-Hoskin** [Working-Title-MSFS-Mods/fspackages#71]
Hi,

Over the past two weeks I have been working on a [CJ4 add-on](https://github.com/J-Hoskin/CJ4-Extended). I thought it would be best to merge it with the work you guys have done on the CJ4, especially since they compliment each other. However, the structure of the repo makes it difficult to contribute as your sifting through files related to other aircraft constantly. Would it not be better to have each of the aircraft in different repos, all under the same organisation?

**Comment by cwburnett** [comment]
In order to keep track of what sim files we're replacing, so as to track where our mods might conflict, we have decided to maintain the existing Asobo structure and work within that framework. As an example, we change (and thus replace) the Airspeed Indicator for all the airliners. If another mod ALSO did this, then we'd have a conflict and one of the two mods won't work. It is for this reason we have structured the repo in this manner. While it does add a layer of complexity, it allows us to clearly see what default files in which default folders we have modified and assists in making decisions about WHERE to make certain changes or fixes, when we should be adding our own version of a file, versus amending a default file that is shared, etc. Hope that helps explain the logic to our organization choice.
