### ISSUE TITLE
ACTIVATE LEG

### ISSUE THREAD

**Issue by ccapilot** [Working-Title-MSFS-Mods/fspackages#72]
Request to have the “ACTIVATE LEG” implemented in the FLP PLN MENU page, so if you have a vector to intercept and join an airways, you can use that function as you normally would in the real unit.

**Comment by K20017** [comment]
Normally when you go direct to a fix, there is an option to select the "INTC CRS" or course to intercept the fix which would then draw out a line from that fix and provide a course.  You could also select a waypoint that is behind the one you want to go to and put it on the very top of the legs page.  What that means is that the FMS thinks you are coming from the behind fix to the new one and it'll draw you a course to intercept.   It's on our list but dealing with flightplan stuff right now is very complex and subject to changes from Asobo.

**Comment by ccapilot** [comment]
thanks for the answer but as far as I know the option to select a course for the INTC CRS option is not working in MSFS G1000 at the moment. May be you could fix that as well, that would be nice, thanks

**Comment by K20017** [comment]
> thanks for the answer but as far as I know the option to select a course for the INTC CRS option is not working in MSFS G1000 at the moment. May be you could fix that as well, that would be nice, thanks

Is this an issue with the G1000 or the CJ4?

**Comment by ccapilot** [comment]
is actually both, none has that capacity at the moment, even the plain DCT does not work correctly, let alone this more "advanced" option of CRS INTCP...

**Comment by mattnischan** [comment]
@ccapilot - The activate leg feature is actually broken from inside the sim. The aircraft code does interface with the in-sim flightplan rather heavily, but for right now calling into the sim to activate a leg doesn't really work, or sorta works but then changes the flightplan or routing in weird ways that we don't have control over.

We're looking at ways to work around that (since we don't have access to the code of the simulator itself, just of the aircraft), which may be a ways off, since they involve a fully custom flightplan system that exists outside of the available in-sim flightplan. Nonetheless, this is on our radar to make work on both the CJ4 and the G1000, and may be made easier if Asobo fixes the bugs with the in-sim flightplan functions.

**Comment by cwburnett** [comment]
This has been addressed in the CJ4, remains open for Garmins
