### ISSUE TITLE
I keep crashing MFD, G1000, Baron, VR, 0.3.4 mod

### ISSUE THREAD

**Issue by KevyKevTPA** [Working-Title-MSFS-Mods/fspackages#748]
I'm not completely sure what I'm doing, but I'm regularly managing to get the MFD to freeze.  It's usually when I'm struggling with the beast trying to get an approach selected, and it just completely stops responding.  At times, I don't even notice at first.  Turning the unit off and back on does not help.  AP controls still work, but the entire display, from the map, to the engine readouts, to the approach window I was using to try to setup my approach just stops.

I haven't used this airplane much, but in the past few days I'm 5 for 5 in managing to get this to happen.  Using the VFR map as a "yoke mounted" GPS has made me able to get to where I'm going, but not the right way!

Help!!

**Comment by darkshine2311** [comment]
Same problem for me the G1000 PFD and MFD are freezing randomly, but generally less than 20 min after takeoff from my flight.
i'm using navigraph airac cycle 2014.

**Comment by Crunchmeister1** [comment]
Same. It typically happens when an approach is activated.

**Comment by daparkerSD** [comment]
I just suffered a PFD freeze in the Baron about an hour into my flight. I had been flying regularly without problems. The MFD remained functional. The GPS-coupled AP routing failed.

**Comment by kmoze2001** [comment]
I've now had the same effect occur when using the 172 G1000.  So far, I'm literally _**100%**_ in having the MFD freeze when activating approaches with the G1000 3.4 version.

I'm more than happy to beta test the 4.0 version, otherwise I'm going to have to completely disable it until it 4.0 goes public as it's not usable for me currently.  And going back to the stock MSFS version feels like going back to the original Doom when one has become used to Doom Eternal.  Yes, the 90s version!

**Comment by Crunchmeister1** [comment]
Same for me. It's 100% reproducible one the Baron and C172. Every single time without failure.

**Comment by szylinski** [comment]
Adding my voice to the chorus on this issue. Only flown with the mod (3.4) twice, but both times I had a screen freeze when trying to load/activate an approach (not sure which stage it actually froze at because I'm not sure what I'm doing a lot of the time!). The first time I was selecting it on the left screen in the corner display, which froze everything on that screen except the terrain, and the second time I froze the right screen when setting it up there.

**Comment by davidebocca** [comment]
Same here, it seems that the issue appears when an approach is selected and the flight plan is shown

**Comment by kaosfere** [comment]
@kmoze2001 @Crunchmeister1 @szylinski @davidebocca 

I have been completely unable to reproduce a lockup on my own, which is really frustrating.   I just went through our GH issues looking for the folks who have mentioned this problem most recently.
 
Assuming you have 100% reproducibility, it would greatly help me if you could provide:

a) a .pln file with the flight plan that locks on you
b) an detailed description of what you do to invoke the lock up, eg, "With the MFD displaying the flight plan page, after passing FIX, hit PROC.   Scroll clockwise to the procedure selection, the scroll clockwise just enough to select RNAV 31.   Hit ENTER.   Then..."
c) let me know if you have Navigraph data installed, and if so, what AIRAC

Hopefully this might give me some more luck in being able to repro.

**Comment by kmoze2001** [comment]
@kaosfere, I can tell you that the last time it happened to me, I was enroute to KORL from KPIE, and was assigned ILS RW25.  As soon as I hit activate, the MFD froze, which is similar behavior to every time it has happened.

Now, having said that, my personal preference is for you guys to forget 3.4 and concentrate your efforts on 4.0, and it is my opinion that you should make the 4.0 beta open to everyone.  I realize you have limited bandwidth, and I feel that it's a waste of resources at this time to spend any more time on 3.4.  I think this behavior in 3.4 is very widespread, and is likely causing people to just stop using it and revert back to the Asobo standard, so it's in everyone's best interest to move everyone over to 4.0 and get it complete as fast as is reasonably possible given the limitations you guys have, and your status as a "non-profit".

Unlike Forrest Gump, that's probably _not_ all I've got to say about that, but I'll go ahead and shut my trap anyway.  Thank you guys for all that you do, I just wish I knew how to code!!
