### ISSUE TITLE
CJ4 0.9.1: Unable to monitor com 2

### ISSUE THREAD

**Issue by AndersHogqvist** [Working-Title-MSFS-Mods/fspackages#816]
I've mapped a button on my Yoke to "Com Receive All Toggle" in FSUIPC and it has let me monitor com 2 while transmitting on com 1. That doesn't work anymore (on IVAO, haven't tested on VATSIM yet). Even if I toggle the com 2 knob in the cockpit and RX is lit up in Altitude (IVAO app) I don't hear anything unless I completely switch to com 2.

**Comment by dga711** [comment]
HI,
since 0.9.0 the plane will itself toggle RECEIVE ALL if both COMs are in RX. Which is the default state now.
Both COMs in RX and the selected COM in TX/RX.
The knob can mute and therefore remove RX from a COM. Which will toggle RECEIVE ALL to 0
The selected COM will always have TX/RX on, no matter the knob.

This works well in vPilot and is in line with other planes that work in that regard.

Does this help you?

**Comment by dga711** [comment]
I think what is happening to you is that you counteract the behavior and toggle RECEIVE ALL in the reverse direction of what the plane sets.

**Comment by AndersHogqvist** [comment]
I will remove the mapping of my button just in case and try again.

**Comment by AndersHogqvist** [comment]
This was a limitation in the IVAO app and it works perfectly in vPilot
