### ISSUE TITLE
G1000: Show procedure routes in real time as they are selected (This one might be hard)

### ISSUE THREAD

**Issue by kaosfere** [Working-Title-MSFS-Mods/fspackages#87]
From @alexismmef:  When Selecting Procedures, the Map will Show in Real Time the Route of Each, as you Go through Them, before selecting. In MFS, it doesn't show anything.

**Comment by knighty** [comment]
This is something I'm working on as part of the rearchitecture I'm doing. Current issue is that it doesn't seem to be possible to do it properly without setting it in a flight plan and then retrieving the waypoints, due to the fact that the procedures don't container waypoints with a full list of lat/long coordinates.
