### ISSUE TITLE
CJ4 v0.10.2 - No ILS frequency in FMC

### ISSUE THREAD

**Issue by slimit75** [Working-Title-MSFS-Mods/fspackages#915]
I saw someone with the same issue on the discord earlier, and I managed to get it myself at a different airport. In my case, I have no 3rd party scenery and was attempting to find the frequency for the ILS 26R at Atlanta. The frequency doesnt show up on either Arrival Data *or* Frequency pages, and is instead replaced with Not a Number on the former page.

![image](https://user-images.githubusercontent.com/45863722/107068040-15a46d80-67ae-11eb-9ed0-3442883ba1e8.png)
![image](https://user-images.githubusercontent.com/45863722/107068055-1e953f00-67ae-11eb-9019-4738f2b44026.png)

**Comment by Kamaniya9** [comment]
There's an explanation in the Discord channel on this. It's due to add-on airports nav data. If it's a stock airport it's the SIM not returning the correct information. Either way just input the frequency manually in TUN and it's good to go. 
![image](https://user-images.githubusercontent.com/71068983/107107203-9c1e8500-686a-11eb-9a35-4fd5d66c5bce.jpeg)

**Comment by slimit75** [comment]
Ah sorry, I dont know how I didnt see that. My bad..
