### ISSUE TITLE
Avionics

### ISSUE THREAD

**Issue by terryherenow** [Working-Title-MSFS-Mods/fspackages#932]
Since MSFS update of the 16th February 2021 , the Avionics no longer turn on...on the CJ4

**Comment by Bernie02** [comment]
Is there a solution yet?

**Comment by terryherenow** [comment]
I re-downloaded V 10.1 ( not V.10.2 which has never worked for me on my machine ) and put into the Community Folder and bingo..problem solved...I just do not know why the bug appeared in my original downloaded version 🤷🏻
Terry


Sent from Yahoo Mail for iPad


On Thursday, February 18, 2021, 12:47 pm, Bernie02 <notifications@github.com> wrote:




Is there a solution yet?

**Comment by Bernie02** [comment]
I loaded the g1000 en g3000 mod and a authorised new livery and it worked  in V10.02 Wonder why? Thanks for te quick reaction. Bern  Van: terryherenowVerzonden: donderdag 18 februari 2021 14:08Aan: Working-Title-MSFS-Mods/fspackagesCC: Bernie02; CommentOnderwerp: Re: [Working-Title-MSFS-Mods/fspackages] Avionics (#932) I re-downloaded V 10.1 ( not V.10.2 which has never worked for me on my machine ) and put into the Community Folder and bingo..problem solved...I just do not know why the bug appeared in my original downloaded version 🤷🏻TerrySent from Yahoo Mail for iPadOn Thursday, February 18, 2021, 12:47 pm, Bernie02 <notifications@github.com> wrote:Is there a solution yet?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
