### ISSUE TITLE
G3000 Mod 0.4.1 freezes MSFS

### ISSUE THREAD

**Issue by flykorni** [Working-Title-MSFS-Mods/fspackages#942]
Hi!

Just tried out the latest mod for the G3000, complete with the roadmap mod. Sometime into the flight I wanted to play around with the map display, especially changing the range on the MFD. This seemed to cause my sim to freeze with no chance to recover.

Hope this will be fixed soon. Otherwise it's a fantastic mod!

Regards, Wolfgang

**Comment by cangianos** [comment]
same for me, freeze MSFS

**Comment by cywang90** [comment]
I will need more details before I can start debugging this, starting with steps to reproduce the freeze.

**Comment by cangianos** [comment]
Hi, Using latest tbm900 mod, if I use the latest G3000 mod the msfs freeze
when we click on FLY. We are not able to use the tbm once we start a new
fly because the sim freeze. Removing the folder g3000 from community the
sim works well. This is with only the last mod of g3000.

---------------------
Cangiano Giulio
Lavoro: +39-333-73-00-511
Casa: (urgenze) 081-379-9111

‐--------------------------

Questo messaggio di posta elettronica contiene informazioni di carattere
confidenziale rivolte esclusivamente al destinatario sopra indicato. E'
vietato l'uso, la diffusione, distribuzione o riproduzione da parte di ogni
altro soggetto. Nel caso aveste ricevuto questo messaggio per errore, siete
pregati di segnalarlo immediatamente al mittente e distruggere quanto
ricevuto (compresi tutti gli eventuali file allegati). Qualsiasi utilizzo
non autorizzato del contenuto di questo messaggio costituisce violazione
dell'obbligo di non prendere cognizione della corrispondenza tra altri
soggetti, salvo più grave illecito e relative conseguenze.

Il mar 23 feb 2021, 00:09 cywang90 <notifications@github.com> ha scritto:

**Comment by cangianos** [comment]
Is is also written that Manifest json file is corrupt when using MOD manager

**Comment by flykorni** [comment]
Yesterday I managed to finish a flight with the TBM, still using the 0.4.1 mod. As I have to test it further I can't tell for sure, but my guess is that it has to do with the amount of details the map has to reproduce when changing the range on the MFD. First I had all the selectable details on which inevitably led to freeze the sim while changing the range multiple times in advance. Reducing the details (eg roads, airways) the freeze didnt happen, but as I allready mentioned...I have to further test it.

Stay tuned!

**Comment by cangianos** [comment]
OK, now I made another test. Back to version 0.4.0 and still freeze. So the problem should be using the last TBM900 improvements mod. Removed the TBM900 mod https://github.com/mixMugz/msfs_tbm930_project the sim works well.!

**Comment by flykorni** [comment]
I did a test yesterday, using the latest mods (G3000 0.4.1, TBM Project 0.5.9) and didn't encounter any freeze situation. Maybe the latest builts did the trick?

**Comment by JG4Thorwald** [comment]
My Game is freezing too. When im sitting in the cockpit and turn the battery on, the game is freezing. Same was with version 4.0
When i use version 3.3 it works fine.

**Comment by cangianos** [comment]
Any news on the fix? I can use the tbm only removing the mod G3000. Otherwise freeze when turning batt on or starting on runway with avionic on.

**Comment by cywang90** [comment]
Unfortunately, I have not been able to reproduce the freeze.

**Comment by cangianos** [comment]
Yeah, I finnally found what mod is incompatible. I forgot to remove the Navigraph beta mod. So if someone is getting freeze of FS2020, just remove the navigraph beta mod. ISSUE solved..

**Comment by cywang90** [comment]
Glad you found the cause.
