### ISSUE TITLE
not sure where to go for help

### ISSUE THREAD

**Issue by jeffsic** [Working-Title-MSFS-Mods/fspackages#962]
K20017, First of all your videos and hard work on the CJ4 are beyond words.  Thanks so much for that.     i am not a pilot but i am so interested in getting the closest real life experience with this plane.  i was afraid to fly for 30 years and sim's plus others have help me overcome my fear.   My problem is i have quite a few questions regarding the CJ4 sim versus real life and i dont know who to go to get answers.   i cant get on the MSFS Forum due to signup/login problems that a lot of people are experiencing so i cant post.  would you be willing to answer my questions or do you know of another place or person i can work with.  For clarity, here are a couple samples of my questions:
1. When you use VNAV on approach it will automatically take you down thru the different altitudes but how do you know that ATC will clear you thru those or  does ATC assume you will go to those altitudes.  both in real life and the game?
2. in real life CJ4 do you typically use a sim brief type program to plan and then enter it into the FMS.  if so then how does all the ATC frequencies along your path, know about this plan. do it somehow go onto an ATC website or something.  Doesnt ATC have to compare your plan with other plans so you dont plan the same exact plan as someone else? 

Sorry to use the issues page for this but cant figure out where to go for help.   thanks in advance for any guidance

**Comment by K20017** [comment]
1) You would never descend below what ATC assigns you.  So the altitude you set in the preselector will never be lower than assigned.  If you are given the words "Descend via the XXXXX arrival, you could then preselect the lowest altitude on the arrival and await further descent instructions when you reach that point.

2) We use fltplan.com for that stuff but before leaving the ground, you'd need an IFR flight plan and would call clearance/ground control to get the clearance.  It's most of the time what you filed but you'll sometimes get an amended route due to weather or ATC airspace congestion.  Your flight plan goes into an ATC system which does a lot more than I know about.  Each controller gets a little strip of paper printed out with the relevant info for your flightplan and when you get handed off to another controller, they know you are coming and where you are going.  If you have two aircraft on the same exact path, one might be delayed a bit to get the appropriate terminal/enroute spacing that is required.  Lots of spacing stuff can happen on the fly because what you filed is not always what happens and ATC might slow one airplane while speeding up another, or turn you off course for a few minutes before bringing you back.

**Comment by jeffsic** [comment]
Can you guys get any more amazing.  Thanks for the response. i am going to go for it with my other questions.  if you honor me with a response great if not i know you are a busy guy and no offense taken.  However, if you do , you have to give me an address or something so i can send you a bottle of scotch or buy you a dinner for your help.

1. Because of the poor battery in the CJ4 in real life do you actually start the engines and let them run while you program the FMS and get ready to taxi.   seems like a long time to enter and have the engines running.  seems like ground crew would say time to leave but maybe real pilots are quick.  i notice when i fly commercial they get a push back then start the engines?
2. Do you know in the sim if you don't put your approach in as you suggested is the real life way, will the sim ATC eventually assign you a runway.  i assume since you plan for a star , they wouldn't typically change that just the approach and runway.
3. In real life and maybe in the sim, if ATC assigns you a runway how do they know if you want RNAV or ILS?
4. i am a little confused on flight change and how it works.  when i fly the CJ4 (again not a pilot) i always use the AP, then set the altitude and use the VS and wheel to change altitude.  you seem to use the Flight Change?  is that normal in real flight? What does flight change do and why is it better? Is it part of the AP?
5. i noticed you use the flight change knob to set the airspeed to 240 kts when climbing but what does that actually do since i an controlling the throttles anyways?
6. In real life does your filing in the fltplan.com website send the plan to the ATC or does the FMS send the plan from the plane and does it have to be done so many hours in advance?
Thanks

Jeff

**Comment by slip664** [comment]
Discord is the best place to get help with most topics: https://discord.gg/cmxCRJX8jG

If you don't have that, we have a guide that covers a vast majority of the operations (based on real world procedures) and is updated pretty regularly: https://docs.google.com/document/d/1qzxPMTSQRkvau8QOi7xUqNvjx9rbww_qHlso5AT5OnI/edit#

Also, this most recent video by FilbertFlies, is very comprehensive and covers much of the operation for the latest version, guided along by Matt, one of our developers:
https://www.youtube.com/watch?v=N5Hs04u1JA4

3. ATIS at bigger airports will usually tell, or they'll just assign you an approach, or you request an approach, or ATC will ask you which approach you want.

6. Websites and apps send the plan right to the FAA. They should be filed at least 30 minutes prior to departure but can be held up to 24 hours, but this all depends on the facility and where your going to/from.

**Comment by jeffsic** [comment]
Thanks guys
