### ISSUE TITLE
NAV/VNAV/LNV1 not engaging.

### ISSUE THREAD

**Issue by darkpq** [Working-Title-MSFS-Mods/fspackages#969]
AP is only working in heading mode right now. LNV1 or NAV modes will not engage with programmed FP in FMC.

**Comment by K20017** [comment]
Can you expand on this?  If you engage NAV, you either need to align yourself to the inbound course or you will need to re-direct to where you want to go.  If you are 5nm away from your LNAV course and press NAV, it's going to arm it but that's all it will do since it doesn't know how you want to intercept it.

**Comment by darkpq** [comment]
I was able to determine that my logitech AP panel (which I've been flying WT cj4 with, but just not using the buttons to adjust anything related to the AP) was causing some sort of hangup. If I disconnect the AP panel after MSFS starts and reconnect it (using my HUB's power buttons) then the NAV/LNV1 mode will engage properly so far. I'm still testing it out, but this is diff from how things were  working from this version of the mod and the hotfix/update from ASOBO.

**Comment by darkpq** [comment]
I usually only use that panel for the flaps switch. So it kind of bugged out/went crazy after the hotfix so I tried unplugging it which allowed the NAV stuff to engage...  idk why!!

**Comment by darkpq** [comment]
I understand the 5NM limitation with LNAV now...  I think I was having a hardware problem AND not understanding that LNV1 wouldn’t engage outside of that distance from the track...  Thanks for the info.
