### ISSUE TITLE
Should we use this format for "custom" imports?

### ISSUE THREAD

**Issue by kaosfere** [Working-Title-MSFS-Mods/fspackages#97]
While looking at some other stuff, I have noticed that we may be able use JS imports like this:

```
Include.addScript("/JS/Services/Aircraft.js");
```

That would allow us to pull dataStorage.js in CommonPFD_MFD.js and avoid changing every *.html files we want to use it and also remove the try/catch blocks in PersistVar.

_Originally posted by @tavip in https://github.com/Working-Title-MSFS-Mods/fspackages/pull/73#r494301484_

**Comment by knighty** [comment]
I would like to do this better too. It's very odd that they don't use a proper importer, instead choosing to do it all in the html files. Could evaluate the feasibility of using `import` here.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

**Comment by dga711** [comment]
My answer from the PR:

Yeah. Actually. I was thinking about also putting this as a comment to include it that way. But then I was like "eh, you have changed the html already anyway" ^^ 
But I didn't think of, that the MFD.js is used by many planes. So @tavip is absolutely right there and you should do it like this.

Only do it for Utils like this though, because ofc it loads in late. addScript also offers a callback as 2nd argument, for when the script is actually loaded, since it can be async.

**Comment by dga711** [comment]
@knighty well they do some kind of weird "importing". You have all the script tags with the import-script attribute, and then they readd them on a page load as proper script-src tags during page load. Only god knows why.
